### ISSUE TITLE
Can't execute the code in my data nor in the example data.

### ISSUE THREAD

**Issue by Alberto3397** [ianvcaldas/smalldisco#2]
Good evening.
I'm getting this error all the time no matter what I do.I'ts important to mention that pandas and all the other dependencies have been correctly installed and versions checked in the current environment. I have double checked it several times and still i dont know how to move on:
(smalldisco) usuario@DESKTOP-H71H9LL:/mnt/d/Alberto/smalldisco/example$ ./disco_test.sh
Running smalldisco siRNA discovery pipeline with command:
snakemake -c1 --configfile .smalldisco/config.json --snakefile /mnt/d/Alberto/smalldisco/example/../workflow/sirna.smk
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                                   count    min threads    max threads
----------------------------------  -------  -------------  -------------
find_putative_sirna_regions               1              1              1
intersect_sirna_and_exons                 1              1              1
locate_sirna_regions                      1              1              1
make_exon_list                            1              1              1
map_antisense_reads                       1              1              1
merge_antisense_reads_from_samples        1              1              1
remove_exon_overlaps                      1              1              1
total                                     7              1              1

Select jobs to execute...

[Tue Apr 16 16:08:22 2024]
rule make_exon_list:
    input: sample.gtf
    output: .smalldisco/sirna/exon-list-with-overlaps.bed
    jobid: 6
    resources: tmpdir=/tmp

Traceback (most recent call last):
  File "/mnt/d/Alberto/smalldisco/example/.snakemake/scripts/tmp6njyy0jb.make-exon-list.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[Tue Apr 16 16:08:22 2024]
Error in rule make_exon_list:
    jobid: 6
    output: .smalldisco/sirna/exon-list-with-overlaps.bed

RuleException:
CalledProcessError in line 96 of /mnt/d/Alberto/smalldisco/workflow/sirna.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /mnt/d/Alberto/smalldisco/example/.snakemake/scripts/tmp6njyy0jb.make-exon-list.py' returned non-zero exit status 1.
  File "/mnt/d/Alberto/smalldisco/workflow/sirna.smk", line 96, in __rule_make_exon_list
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/d/Alberto/smalldisco/example/.snakemake/log/2024-04-16T160821.765588.snakemake.log
Usage: smalldisco.py tail [OPTIONS] BEDFILE BAMFOLDER
Try 'smalldisco.py tail --help' for help.

Error: Invalid value for 'BEDFILE': Path 'sirna.bed' does not exist.

Thank you very much for your time in advance.

**Comment by ianvcaldas** [comment]
Hi Alberto,

It looks like pandas isn't being found from within smalldisco. Since your environment is set up properly and looks to be activated in your example code, I wouldn't expect that to happen. I suspect that your problem might have to do with spawning a new shell – when you run the example bash script, the sub-shell that gets spawned to run that script does not have access to the conda environment for some reason. (In my testing, this doesn't happen, but I can imagine that it would break under some specific computer setups.) What happens if you try running smalldisco manually, instead of through the example script? Like so:

```bash
conda activate smalldisco
cd smalldisco/example
python ../smalldisco.py sirna -o sirna.bed -a sample.gtf BAM/
```

**Comment by Alberto3397** [comment]
No, it still does not work... Can't find pandas, same error, but it 's there.
I also tried to modify some *.smk files and scripts, but same error as well.
![Captura](https://github.com/ianvcaldas/smalldisco/assets/71329748/9577843a-3f13-4abf-9607-a15a4e79bc90)

**Comment by ianvcaldas** [comment]
What happens if you just try to import pandas from within your conda environment? Like so:

```bash
conda activate smalldisco
python
```

And from within Python:

```python
import pandas as pd
```

If that works fine, then I don't know what is causing your problem. I have just tested a fresh install of smalldisco on a Linux computer running Ubuntu 20.04.5, and it works. I am unable to reproduce the error you are seeing.

**Comment by Alberto3397** [comment]
Yeah, that works, but still get the same error... :(
